[options]
Architecture = auto
HoldPkg = pacman glibc
CheckSpace
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 10

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib] # 윈도우 앱 호환(Wine)을 위해 필수
Include = /etc/pacman.d/mirrorlist

[cloudos-repo]
SigLevel = Optional TrustAll
Server = file:///opt/cloudos-repo
